// constants/audit.js

export const MODULES = {
  EMPLOYEE: "EMPLOYEE",
  ATTENDANCE: "ATTENDANCE",
  LEAVE: "LEAVE",
  PAYROLL: "PAYROLL",
  SALARY: "SALARY",
  PERFORMANCE: "PERFORMANCE",
  RECRUITMENT: "RECRUITMENT",
  DOCUMENTS: "DOCUMENTS",
};

export const ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  VIEW: "VIEW",
  LOGIN: "LOGIN",
};